// AUTH
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const RESET_ERRORS = "RESET_ERRORS";
export const LOGIN_USER = "LOGIN_USER";

// Organization
export const POST_ORGANIZATION = "POST_ORGANIZATION";
export const POST_ORG_USER = "POST_ORG_USER";
export const POST_ORG_PROPERTY = "POST_ORG_PROPERTY";
export const GET_ORGANIZATION = "GET_ORGANIZATION";
export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const GET_ORG_DATA = "GET_ORG_DATA";
export const EDIT_ORGANIZATION = "EDIT_ORGANIZATION";
export const EDIT_ORG_USER = "EDIT_ORG_USER";
export const EDIT_ORG_PROPERTY = "EDIT_ORG_PROPERTY";
export const SET_CURRENT_ORGANIZATION = "SET_CURRENT_ORGANIZATION";
export const SEARCH_ORGANIZATIONS = "SEARCH_ORGANIZATIONS";
export const ORGANIZATION_LOADING = "ORGANIZATION_LOADING";
export const ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND";
export const CLEAR_CURRENT_ORGANIZATIONS = "CLEAR_CURRENT_ORGANIZATIONS";
export const SET_LOADING_ORG = "SET_LOADING_ORG";

// PROPERTIES

export const POST_PROP_USER = "POST_PROP_USER";
export const EDIT_PROP_USER = "EDIT_PROP_USER";
export const GET_PROP_DATA = "GET_PROP_DATA";
export const SET_LOADING_PROP = "SET_LOADING_PROP";
export const SET_CURRENT_PROPERTY = "SET_CURRENT_PROPERTY";

// USER
export const POST_USER = "POST_USER";
export const GET_USER = "GET_USER";
export const GET_USERS = "GET_USERS";
export const EDIT_USER = "EDIT_USER";
export const SEARCH_USERS = "SEARCH_USERS";
export const USER_LOADING = "USER_LOADING";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const CLEAR_CURRENT_USERS = "CLEAR_CURRENT_USERS";
export const SET_LOADING_USER = "SET_LOADING_USER";

// FORM
export const SET_FORM = "SET_FORM";
export const SAVE_FORM = "SAVE_FORM";

// NOTIFICATION
export const LOG_ERRORS = "LOG_ERRORS";
export const LOG_SUCCESS = "LOG_SUCCESS";
