const SUBMIT_STARTED = "SUBMIT_STARTED";
const SUBMIT_ERROR = "SUBMIT_ERROR";
const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const RESET_ERRORS = "RESET_ERRORS";
export const LOGIN_USER = "LOGIN_USER";
export const UPDATE_USER = "UPDATE_USER";
